Check a Sem ver string

diff --git a/.github/workflows/bumpup.yml b/.github/workflows/bumpup.yml
--- a/.github/workflows/bumpup.yml
+++ b/.github/workflows/bumpup.yml
@@ -30,6 +30,13 @@ jobs:
       env:
         VERSION: ${{ github.event.inputs.gem-version }}
       run: |
+        regex="\(0\|[1-9][0-9]*\).\(0\|[1-9][0-9]*\)\.\(0\|[1-9][0-9]*\)\.\([0-9]*\)"
+        if [[ "${VERSION}" =~ $regex ]]; then
+          echo OK
+        else
+          echo "::error::Invalid version format."
+          exit 1
+        fi
         sed -i "s/VERSION = .*/VERSION = '${VERSION}' /" lib/jpostcode/version.rb
 
     - name: bundle install
